### PR TITLE
Update pl.yml

### PR DESCRIPTION
**Pull request by radex**
Added `title_by_author` translation. There's no good way to translate "by" here (the direct translation feels awkward), so I just used em dash here.

(Chyba, że ktoś ma lepszy pomysł? :P)

### CODE REVIEW

**Comment by soffes** [comment]
Sounds good :) Can you add like too?

**Comment by radex** [comment]
Sure! Didn't notice it.

Added (and squashed commits)

**Comment by soffes** [comment]
Perfect. Thanks!

**Comment by radex** [comment]
No problem! Glad I could help :)

**Pull request merged**
