### PR TITLE
Update de.yml

### PR DESCRIPTION
**Pull request by benjaminfritz**
Some small corrections and additions.

### CODE REVIEW

**Comment by soffes** [comment]
Thanks! Can you add like?

**Comment by benjaminfritz** [comment]
@soffes Sure, as a label for a button (Facebook-style)?

**Comment by steinerl** [comment]
Uh, ok, you changed the Austrian German to standard German.
@soffes should I add a de-AT file?

**Comment by benjaminfritz** [comment]
@steinerl In what regard? I guess we can find a consensus or just stick with your version when in doubt :) No need for a de-AT version IMO.

**Comment by soffes** [comment]
@steinerl if you think it's necessary. In my past experience, I've only done country specific for Portuguese and Chinese since they are so different. If you think it's necessary, I'm open to it though.

**Comment by soffes** [comment]
@benjaminfritz yes. "Like" is the label of the heart button at the bottom of the page when viewing [a post](http://sam.roon.io/onward).

**Comment by steinerl** [comment]
@soffes it is not necessary, because the differences are small and if you think 2 versions are hard to maintain in the future, we should definitely stick with @benjaminfritz's version.

**Comment by soffes** [comment]
Okay. Thanks @steinerl!

**Comment by benjaminfritz** [comment]
@steinerl Good job btw! @soffes Do you want the exact same wording as on Facebook or something more original with the same meaning behind it?

**Comment by soffes** [comment]
I think the same as Facebook would be the most clear. How does that sound?

**Comment by benjaminfritz** [comment]
@soffes Done.

**Pull request merged**
